___
name: control
host: control
become: yes
 - name: httpd installation
   yum: 
     name: httpd
     state: present
 - name: service start& enabled
    service:
     name: httpd
     state: started
     enabled: yes

