---
- name: server
  hosts: control
  become: yes
  tasks:
    - name: shell cmds
      shell: systemctl status httpd
    - name: copy
      copy:
        src: index.html
        dest: /var/www/html/index.html
        backup: yes
    - name: fetch data
      fetch:
        src: /var/www/html/*
        dest: /Users/sabarish/Desktop/ansible/data/*
        flat: yes
