---
- name: server
  hosts: control
  become: yes
  tasks:
    - name: shell cmds
      shell: systemctl status httpd
    - name: dir
      shell: |
        mkdir /home/ec2-user/sabarish
        touch /home/ec2-user/sabarish/shell.yaml
